import clr
import os
clr.AddReference(os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "..",  'lib', 'UnderAutomation.Staubli.dll')))
from UnderAutomation.Staubli.Soap.Errors import StartApplicationError as start_application_error

class StartApplicationError(int):
	MemoryFull = int(start_application_error.MemoryFull)
	LibraryBusy = int(start_application_error.LibraryBusy)
	LibraryInvalidZip = int(start_application_error.LibraryInvalidZip)
	DataNotFound = int(start_application_error.DataNotFound)
	DataBusy = int(start_application_error.DataBusy)
	DataInvalidName = int(start_application_error.DataInvalidName)
	DataAlreadyExists = int(start_application_error.DataAlreadyExists)
	DataInvalidSize = int(start_application_error.DataInvalidSize)
	DataNotAnArray = int(start_application_error.DataNotAnArray)
	RoutineInvalidName = int(start_application_error.RoutineInvalidName)
	RoutineAlreadyExists = int(start_application_error.RoutineAlreadyExists)
	RoutineNameTooLong = int(start_application_error.RoutineNameTooLong)
	RoutineInvalidParamPosition = int(start_application_error.RoutineInvalidParamPosition)
	RoutineNotFound = int(start_application_error.RoutineNotFound)
	RoutineBusy = int(start_application_error.RoutineBusy)
	ProjectBusy = int(start_application_error.ProjectBusy)
	ProjectInvalidName = int(start_application_error.ProjectInvalidName)
	ProjectInvalidAlias = int(start_application_error.ProjectInvalidAlias)
	ProjectAliasAlreadyUsed = int(start_application_error.ProjectAliasAlreadyUsed)
	ProjectAlreadyExists = int(start_application_error.ProjectAlreadyExists)
	ProjectCodeError = int(start_application_error.ProjectCodeError)
	ProjectDataError = int(start_application_error.ProjectDataError)
	StartRoutineNotFound = int(start_application_error.StartRoutineNotFound)
	ProjectInvalidMain = int(start_application_error.ProjectInvalidMain)
	ProjectInvalidProject = int(start_application_error.ProjectInvalidProject)
	StopRoutineNotFound = int(start_application_error.StopRoutineNotFound)
	ProjectInvalidDestructor = int(start_application_error.ProjectInvalidDestructor)
	ProjectDefaultStackTooSmall = int(start_application_error.ProjectDefaultStackTooSmall)
	ProjectAlreadyRunning = int(start_application_error.ProjectAlreadyRunning)
	ProjectAlreadyEnding = int(start_application_error.ProjectAlreadyEnding)
	ProjectLocked = int(start_application_error.ProjectLocked)
	ProjectFileError = int(start_application_error.ProjectFileError)
	ProjectFilemanagerNotFound = int(start_application_error.ProjectFilemanagerNotFound)
	ProjectLibraryError = int(start_application_error.ProjectLibraryError)
	ProjectUnresolvedSymbol = int(start_application_error.ProjectUnresolvedSymbol)
	ProjectInconsistantResolvedSymbol = int(start_application_error.ProjectInconsistantResolvedSymbol)
	ProjectInterfaceStillUsed = int(start_application_error.ProjectInterfaceStillUsed)
	ProjectUsedAsStruct = int(start_application_error.ProjectUsedAsStruct)
	ProjectInterfaceTaskNotKilled = int(start_application_error.ProjectInterfaceTaskNotKilled)
	ProjectInvalidTypename = int(start_application_error.ProjectInvalidTypename)
	ProjectTypenameAlreadyUsed = int(start_application_error.ProjectTypenameAlreadyUsed)
	ProjectTypeProjectError = int(start_application_error.ProjectTypeProjectError)
	ProjectTypeBusy = int(start_application_error.ProjectTypeBusy)
	ProjectCircularReference = int(start_application_error.ProjectCircularReference)

	def __repr__(self):
		for name, value in vars(StartApplicationError).items():
			if not name.startswith('_') and isinstance(value, int) and value == self:
				return name
		return str(int(self))
